### ISSUE TITLE
dataset is not clear

### ISSUE THREAD

**Issue by Elainemilier** [NikV-JS/U-Det#2]
Can you disclose the data tree of this project?

**Comment by Nik-V9** [comment]
The dataset structure is the same as the one available at https://luna16.grand-challenge.org/Data/ . Additionally, Inside the data root folder (i.e. where you have your data stored) you should have two folders: one called imgs and one called masks. All models, results, etc. are saved to this same root directory. The argument --data_root_dir is the only required argument and should be set to the directory containing your imgs and masks folders.

**Comment by Elainemilier** [comment]
Thank you very much for your reply!

**Comment by Elainemilier** [comment]
But I'd like to ask you how the data in your masks folder is generated?

**Comment by Nik-V9** [comment]
No problem, the LUNA16 Data is processed into images and masks with the help of RadIO python library. The required resources are present here: https://analysiscenter.github.io/radio/intro/preprocessing.html

**Comment by Elainemilier** [comment]
Thank you very much !
