### ISSUE TITLE
Question for dataset structure

### ISSUE THREAD

**Issue by yuchen02** [NikV-JS/U-Det#3]
Dear Sir:
There was a problem running your code. Now, I know that you are using the LUNA16 data set, and the data set contains "imgs" and "masks" folders. But I don't know what files are contained in the folder. I tried to put the'.mhd' file into the img folder, and put the contents of subset0-subset10 into the masks folder. The split_lists folder has been successfully generated, but it cannot be read correctly. Can you show the detailed structure of the dataset? Like below
+ --- imgs
| xxx
| xxx
+ ---masks
| xxx
| xxx
+ --- Split list
I want to know what file formats (.mhd or other formats) are contained in the "imgs" and "masks" folders.
Sincerely hope that you can show the processing method of the dataset, and I wish you a happy work!

**Comment by Nik-V9** [comment]
Hello, Thank you for showing interest in the code. Yes, the structure of the data used for the project is similar to the official Luna16 data but one small change is that the .mhd and annotation files are preprocessed into slice images and segmentation masks. They are contained in the imgs and masks and are of image format. Please refer to Issue #2  where I have given the resource (library) used for data pre-processing.

**Comment by Nik-V9** [comment]
The readme file has also been updated, clarifying the same. Please refer to that resource for pre-processing LUNA16 data.

**Comment by yuchen02** [comment]
Thanks for your reply, I got it

**Comment by yuchen02** [comment]
After I preprocessed Luna16 data according to the method you provided, I got the following data
/home/yuchen/download/output
├─1.3.6.1.4.1.14519.5.2.1.6279.6001.248425363469507808613979846863
│ ├─origin
│ │ └─data.pkl
│ ├─spacing
│ │ └─data.pkl
│ ├─images
│ │ ├─data.blk
│ │ └─data.shape
│ └─masks
│ ├─data.blk
│ └─data.shape
I don’t know if it is consistent with the picture format you mentioned, but I have never seen a .blk or .shape file. After carefully analyzing the RadIO library, I feel that it is far from the data you described. I'm looking forward to your help.

**Comment by Nik-V9** [comment]
The .blk data you have obtained is batched data. If you want to use the code as-is, you will have to save each image/mask of the batch in your desired format to the imgs and masks folder using a for-loop looping across all the batches when you preprocess. You can also modify the current code to leverage the RadIO data directly in terms of batches.  Feel free to refer to the whole RadIO documentation: https://analysiscenter.github.io/radio/index.html By the way, the picture format I am referring to is .'png' (standard image format); it can be '.jpg' also.

**Comment by yuchen02** [comment]
Thanks a million for your help

**Comment by yuchen02** [comment]
I tried the ideas you provided but failed. If possible, I hope you can publish the preprocessed code. Thank you for your patience.

**Comment by yuchen02** [comment]
@NikV-JS Hello sir:
I used the method you provided to generate some data, the shape of which was (512, 512, 4), when I ran U-Det, I found that it was not appropriate, so I made the following changes:
-----------------------
image = np.load(join(args.data_root_dir,'imgs','images_'+train_list[0][0]),allow_pickle=True).T
-----------------------
image = Image.open(join(args.data_root_dir,'imgs','images_'+train_list[0][0]))
    image =np.array(image)
    image =image[:,:,0:1]
------------------------
The train_split_0_class_weights.npy file was successfully generated, but an error was reported:
Traceback (most recent call last):
  File "main.py", line 168, in <module>
    main(arguments)
  File "main.py", line 81, in main
    train(args, train_list, val_list, model_list[0], net_input_shape)
  File "C:\Users\dell\Desktop\U-Det\train.py", line 137, in train
    verbose=1)
  File "E:\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "E:\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 235, in fit
    use_multiprocessing=use_multiprocessing)
  File "E:\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 593, in _process_training_inputs
    use_multiprocessing=use_multiprocessing)
  File "E:\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 706, in _process_inputs
    use_multiprocessing=use_multiprocessing)
  File "E:\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\keras\engine\data_adapter.py", line 747, in __init__
    peek, x = self._peek_and_restore(x)
  File "E:\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\keras\engine\data_adapter.py", line 850, in _peek_and_restore
    peek = next(x)
  File "C:\Users\dell\Desktop\U-Det\Data_Loader\load_3D_data.py", line 291, in __next__
    return self.it.__next__()
  File "C:\Users\dell\Desktop\U-Det\Data_Loader\load_3D_data.py", line 343, in generate_train_batches
    img_batch[count, :, :, :] = train_img[:, :, j:j + numSlices * (subSampAmt+1):subSampAmt+1]
ValueError: could not broadcast input array from shape (512,4,1) into shape (512,512,1)
Can you tell me the shape of the picture you entered? Or share a few pieces of your training data, thanks

**Comment by Mehedi071** [comment]
@yuchen02 how was your dice_score?
could you share your pre-processng file?
